# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

num = 1

while num < 10:
  i = 1
  if num % 2 == 1:
    i = 1
  else:
    i = 2
  while i < 10 :
      print(num,'X',i,'=',num * i)
      i += 2


  num += 1