# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

while True:
 insertCoin = int(input('돈을 넣어주세요 >> '))
 drink = int(input('메뉴를 골라주세요 1.오렌지주스 2.사이다 3.물>> '))
 coin = insertCoin

 if drink == 1:
   if coin >= 100:
      remain = coin -100
      print('오렌지주스가 곧 제공됩니다')
      print('잔돈은 {}원 입니다'.format(remain))
   else:
      print('잔액이 부족합니다.')
 if drink == 2:
   if coin >= 200:
      remain = coin -200
      print('커피가 곧 제공됩니다')
      print('잔돈은 {}원 입니다'.format(remain))
   else:
      print('잔액이 부족합니다.')
 if drink == 3:
   if coin >= 300:
      remain = coin -300
      print('콜라가 곧 제공됩니다')
      print('잔돈은 {}원 입니다'.format(remain))
   else:
      print('잔액이 부족합니다.')
else:
  print('메뉴를 다시 입력해주세요')

coin= 0