# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

PI = 3.14
double_PI = PI * 2
print(double_PI)
5.5 * 5.5 * PI

A = 10 * 4 *(1/2)
B= 9 * 5 * (1/2)
print(A == B)


(92 * 4) - 95 - 88 - 90