# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

i = 1
k = 2
while i < 10:
  j = 1
  while j < 10 :
      print(i,'X',j,'=',i * j)
      j += 2



  i += 2
while k < 10:
  l = 2
  while l < 10:
     print(k,'X',l,'=',k * l)
     l += 2
  k += 2