# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

while True:
  n = (int(input()))
  if n <= 0 :
    print("invalid input")
  a="*"
  for i in range(1,n + 1):
    print(a * i)