# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

while True:
 try:
    n = int(input("n 값을 입력하세요: "))  # 사용자 입력을 정수로 변환
    if n <0 or n>=10 :
        print("제대로 값을 입력하세요.")
    else:
        num = 1
        rows = 3  # 삼각형 줄 수

        for i in range(1, rows + 1):  # 줄 수만큼 반복
            spaces = rows - i  # 왼쪽 공백 개수 계산
            print(" " * spaces, end = "")  # 공백 출력 (줄바꿈 없이)

            for j in range(2 * i - 1):  # 각 줄의 숫자 개수 (1, 3, 5...)
                if num <= n:
                    print(num, end = "")  # 숫자 출력
                else:
                    print(" ", end = "")  # 숫자가 n보다 크면 공백 출력
                num += 1  # 숫자 증가
            print()  # 줄바꿈
 except ValueError:
    print("제대로 값을 입력하세요.")  # 입력값이 숫자가 아닐 경우 처리