# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

def check_prime_num(x):
    if x < 2:
        return False  # 2보다 작은 수는 소수가 아님
    for i in range(2, x):
        if x % i == 0:
            return False
    return True

while True:
    try:
        number = int(input('판별할 자연수를 입력하세요: '))
        if number < 1:
            raise ValueError("1 이상의 자연수를 입력해야 합니다.")

        # 판별 결과 출력
        if check_prime_num(number):
            print(f"{number}는 소수입니다.")
        else:
            print(f"{number}는 소수가 아닙니다.")
        break  # 정상적으로 끝나면 루프 종료
    except ValueError as e:
        print(f"잘못된 입력입니다: {e}")