# -*- coding: utf-8 -*-
"""Colaboratory에 오신 것을 환영합니다

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

num=1

for i in range(1, 6):
  num += 1
  for j in range(i, i+5):
    if(j == i + 4):
      print(j, end = "\n")
    else:
     print(j, end = "")

