# -*- coding: utf-8 -*-
"""Colaboratory에 오신 것을 환영합니다

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

while True:
    try:
        n = int(input('열을 입력하세요.'))
        m = int(input('행을 입력하세요.'))

        for i in range(1, n+1):
            for j in range(i, i + m):
                print(j, end = "")
            print(end = "\n")
    except ValueError:
        print("제대로 입력하세요")

