# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

def interest_year(p, r, n):
    return p * (1 + r) ** n  # 들여쓰기 추가

p = 30000000
r = 0.051
n = 3

result = interest_year(p, r, n)
print('원금: {0}, 이자: {1}'.format(p, result - p))