# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

def interest_year(p, r, n):
    return p * (1 + r) ** n  # 이자 계산 함수

while True:
    try:
        # 사용자 입력 받기
        p = int(input('원금을 입력하세요: '))
        r = float(input('이율을 입력하세요 (예: 0.051): '))
        n = int(input('기간을 입력하세요 (년): '))

        # 음수나 0 입력 시 예외 발생
        if p <= 0 or r <= 0 or n <= 0:
            raise ValueError("입력값은 0보다 커야 합니다.")

        # 함수 호출
        result = interest_year(p, r, n)

        # 결과 출력
        print('원금: {:,}원, 이자: {:,.2f}원'.format(p, result - p))
        break  # 성공 시 반복 종료
    except ValueError as e:
        print(f"잘못된 입력입니다: {e}")