# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwxY138PKiN62W3xvIG87EBRo2lRqyVJ
"""

while True:
    try:
        insertCoin = int(input('돈을 넣어주세요 >> '))
        if insertCoin < 0:
            print('돈은 0원 이상만 넣을 수 있습니다. 다시 시도해주세요.\n')
            continue

        print("메뉴를 골라주세요 1.오렌지주스(100원) 2.사이다(200원) 3.물(300원)")
        drink = int(input('번호를 입력해주세요 >> '))

        if drink not in [1, 2, 3]:
            print('올바른 메뉴 번호를 입력해주세요.\n')
            continue

        coin = insertCoin

        if drink == 1:
            if coin >= 100:
                remain = coin - 100
                print('오렌지주스가 곧 제공됩니다')
                print('잔돈은 {}원 입니다\n'.format(remain))
            else:
                print('잔액이 부족합니다.\n')
        elif drink == 2:
            if coin >= 200:
                remain = coin - 200
                print('사이다가 곧 제공됩니다')
                print('잔돈은 {}원 입니다\n'.format(remain))
            else:
                print('잔액이 부족합니다.\n')
        elif drink == 3:
            if coin >= 300:
                remain = coin - 300
                print('물이 곧 제공됩니다')
                print('잔돈은 {}원 입니다\n'.format(remain))
            else:
                print('잔액이 부족합니다.\n')

    except ValueError:
        print('자연수만 입력해주세요. \n')